name: Check Style

on:
  workflow_call:

jobs:
  check-style:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Run Betterleaks
        id: betterleaks
        continue-on-error: true
        # version 0.1.0
        uses: dortort/betterleaks-action@cd0b905aa4befb8f42f8b1ab98150180c9e77515
        with:
          version: "v1.9.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Betterleaks report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: betterleaks-report
          path: betterleaks-report.sarif
          if-no-files-found: warn

#       NEEDS POWER-WASHING GIT HISTORY, DO DIRECTLY IN MAIN
#      - name: Fail if Betterleaks found leaks
#        if: steps.betterleaks.outcome == 'failure'
#        run: exit 1

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"

      - name: Check Code Style
        run: mvn --update-snapshots --no-transfer-progress spotless:check pmd:check
