name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version:
          - "11"
          - "8"
        distribution:
          - "temurin"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          cache: "maven"

      - name: Verify with Maven
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
          WORKFLOW_ID: ${{ secrets.WORKFLOW_ID_SE_TESTS }}
          MINDEE_V2_API_KEY: ${{ secrets.MINDEE_V2_SE_TESTS_API_KEY }}
          MINDEE_V2_FINDOC_MODEL_ID: ${{ secrets.MINDEE_V2_SE_TESTS_FINDOC_MODEL_ID }}
          MINDEE_V2_SE_TESTS_BLANK_PDF_URL: ${{ secrets.MINDEE_V2_SE_TESTS_BLANK_PDF_URL }}
        run: |
          mvn clean test-compile failsafe:integration-test failsafe:verify
