name: Test Code Samples
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_sample_code:
    name: Test Sample Code
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        java-version:
          - "21"
          - "17"
          - "11"
          - "8"
        distribution:
          - "temurin"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          cache: "maven"

      - name: Install mindee-java-api
        run: mvn clean install -DskipTests

      - name: Tests sample code
        run: |
          ./tests/test_code_samples.sh ${{ secrets.MINDEE_ACCOUNT_SE_TESTS }} ${{ secrets.MINDEE_ENDPOINT_SE_TESTS }} ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
