name: Checks

on:
  - push

jobs:
  check-style:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: "maven"

      - name: Check Code Style
        run: mvn --update-snapshots --no-transfer-progress checkstyle:check
