name: Crontab

on:
  schedule:
  - cron: '33 0 * * *'

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  codeql:
    uses: mindee/mindee-api-java/.github/workflows/_codeql.yml@main
  test_code_samples:
    uses: mindee/mindee-api-java/.github/workflows/_test-code-samples.yml@main
    secrets: inherit
  test_cli:
    uses: mindee/mindee-api-java/.github/workflows/_test-cli.yml@main
    secrets: inherit
