name: Integration Tests

on:
  pull_request:
  workflow_run:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:
jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version:
          - "11"
          - "8"
        distribution:
          - "temurin"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          cache: "maven"

      - name: Verify with Maven
        env:
          MINDEE_API_KEY: ${{ secrets.MINDEE_API_KEY_SE_TESTS }}
        run: |
          mvn clean test-compile failsafe:integration-test failsafe:verify
