name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  static_analysis:
    uses: ./.github/workflows/_static-analysis.yml
  build:
    uses: ./.github/workflows/_build.yml
    needs: static_analysis
    secrets: inherit
  codeql:
    uses: ./.github/workflows/_codeql.yml
    needs: build
    permissions:
      actions: read
      security-events: write
  test_integrations:
    uses: ./.github/workflows/_test-integrations.yml
    needs: build
    secrets: inherit
  test_code_samples:
    uses: ./.github/workflows/_test-code-samples.yml
    needs: build
    secrets: inherit
