name: Pull Request

on:
  pull_request:

jobs:
  checkstyle:
    uses: mindee/mindee-api-java/.github/workflows/_checkstyle.yml@main
  build:
    uses: mindee/mindee-api-java/.github/workflows/_build.yml@main
    needs: checkstyle
    secrets: inherit
  codeql:
    uses: mindee/mindee-api-java/.github/workflows/_codeql.yml@main
    needs: build
  integration_tests:
    uses: mindee/mindee-api-java/.github/workflows/_integration-tests.yml@main
    needs: build
    secrets: inherit
  test_code_samples:
    uses: mindee/mindee-api-java/.github/workflows/_test-code-samples.yml@main
    needs: build
    secrets: inherit
